### ISSUE TITLE
Tutorial about how to use this package

### ISSUE THREAD

**Issue by lydiazcheng** [HyroVitalyProtago/ControllerEmulator#2]
Thanks for the amazing work!

I am a new start of the Google Daydream and wondering how to use your package? Could you pls give any steps?

Thanks a lot!

**Comment by HyroVitalyProtago** [comment]
Hi & thanks! This is a unity project, so you can download the "optimized" branch, launch the project into unity, build the project for ios on a mac, that will launch xcode, and after that, build/push the xcode project on your phone. If you haven't an ios developer licence (like me), the app will run only 1 week, after that, you need to re-push the xcode project on your phone. Good luck!

**Comment by lydiazcheng** [comment]
Thanks for your nice reply! I'll try it :)

**Comment by HyroVitalyProtago** [comment]
My pleasure. Tell me if you succeed ;)
